---
namespace: "phlpdtrt"
name: "microk8s"
readme: "README.md"
version: "1.0.0"
authors:
  - Philipp Dittert <philipp.dittert@gmail.com>
dependencies:
  "community.general": "*"
license:
  - "MIT"
repository: "https://www.github.com/phlpdtrt/ansible-role.microk8s"
...
