---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /sys/kernel/security:/sys/kernel/security:rw
      - ${PWD}:/etc/ansible/roles/phlpdtrt.microk8s:ro
      - ${PWD}/library:/root/.ansible/plugins/modules:ro
    privileged: true
    pre_build_image: true
    tty: true
    environment:
      container: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
...
