---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: node1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${PWD}:/etc/ansible/roles/phlpdtrt.microk8s:ro
      - ${PWD}/library:/root/.ansible/plugins/modules:ro
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    tty: true
    environment:
      container: docker
    docker_networks:
      - name: private_network
        ipam_config:
          - subnet: "192.168.0.0/16"
            gateway: "192.168.0.254"
    networks:
      - name: private_network
        ipv4_address: "192.168.0.1"

  - name: node2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${PWD}:/etc/ansible/roles/phlpdtrt.microk8s:ro
      - ${PWD}/library:/root/.ansible/plugins/modules:ro
    privileged: true
    pre_build_image: true
    tty: true
    environment:
      container: docker
    docker_networks:
      - name: private_network
        ipam_config:
          - subnet: "192.168.0.0/16"
            gateway: "192.168.0.254"
    networks:
      - name: private_network
        ipv4_address: "192.168.0.2"
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
  inventory:
    hosts:
      microk8s_HA:
        hosts:
          node1: {}
          node2: {}
...
