---
name: CI

'on':
  push:
    branches:
      - master

defaults:
  run:
    working-directory: phlpdtrt.microk8s

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  super-linter:
    name: Github Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base with github super-linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phlpdtrt.microk8s
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: phlpdtrt.microk8s

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install pip dependencies
        run: pip3 install -r requirements.txt

      - name: Install ansible dependencies
        run: ansible-galaxy install -r requirements.yml

      - name: Run Molecule tests
        run: |
          for i in {1..3}; do
            molecule test && break
          done
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}
